NAMES = [
    "embeddings",
    "embeddings-diff-starts",
    "embeddings-shift",
    "embeddings-text-shift",
    "embeddings-text-shift-05",
    "embeddings-wrong-start",
    "embeddings-wrong-start-longer",
    "embeddings-wrong-start-longer-text",
    "embeddings-wrong-start-longer-50",
    "embeddings-wrong-start-longer-300",
    "embeddings-wrong-start-300-from-200",
    "embeddings-reversed-noise",
    "embeddings-no-classifier-free-guidance",
    "embeddings-noise-100-everytime",
    "embeddings-wrong-start-reversed-steps",
    "embeddings-reversed-noise-big-classifier-free-guidance",
    "black-box",
    "embeddings-carlini",
]

LABELS = [
    "Partial denoising",
    "Partial denoising non-iterative",
    "Partial denoising latent shift",
    "Partial denoising text shift",
    "Partial denoising bigger text shift",
    "Partial denoising wrong start",
    "Full denoising start 100",
    "Full denoising start 100 text shift",
    "Full denoising start 50",
    "Full denoising start 300",
    "Short denoising start 300",
    "Reversed denoising",
    "Full denoising 300 no cfg",
    "Full denoising 100 non-iterative",
    "Reversed noising regular cfg",
    "Reversed noising",
    "Black-box",
    "Baseline loss threshold",
]


ATTACKS = {
    "embeddings": {
        "start": 300,
        "stop": 50,
        "step": 10,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 300,
        "fix-noise-step": False,
        "reverse-noise": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-diff-starts": {
        "start": 300,
        "stop": 50,
        "step": 10,
        "iterative": False,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-shift": {
        "start": 300,
        "stop": 50,
        "step": 10,
        "iterative": True,
        "shift-latent-idx": 250,
        "shift-text": False,
        "shift-by": 0.1,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-text-shift": {
        "start": 300,
        "stop": 50,
        "step": 10,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": True,
        "shift-by": 0.1,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-text-shift-05": {
        "start": 300,
        "stop": 50,
        "step": 10,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": True,
        "shift-by": 0.5,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-wrong-start": {
        "start": 300,
        "stop": 50,
        "step": 10,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 100,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-wrong-start-longer": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 100,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-wrong-start-longer-text": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": True,
        "shift-by": 0.1,
        "start-noise-step": 100,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-wrong-start-longer-50": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 50,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-wrong-start-longer-300": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-wrong-start-300-from-200": {
        "start": 200,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-reversed-noise": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 100,
        "reverse-noise": True,
        "fix-noise-step": False,
        "classifier-free-guidance": 100,
    },
    "embeddings-no-classifier-free-guidance": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 0,
    },
    "embeddings-noise-100-everytime": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": False,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 100,
        "reverse-noise": False,
        "fix-noise-step": True,
        "classifier-free-guidance": 100,
    },
    "embeddings-wrong-start-reversed-steps": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": True,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 100,
        "reverse-noise": True,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-reversed-noise-big-classifier-free-guidance": {
        "start": 900,
        "stop": 0,
        "step": 100,
        "iterative": False,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 100,
        "reverse-noise": True,
        "fix-noise-step": False,
        "classifier-free-guidance": 100,
    },
    "black-box": {
        "start": 1000,
        "stop": 0,
        "step": 20,
        "iterative": False,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 1000,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
    "embeddings-carlini": {
        "start": 300,
        "stop": 300,
        "step": 20,
        "iterative": False,
        "shift-latent-idx": -1,
        "shift-text": False,
        "shift-by": 0,
        "start-noise-step": 300,
        "reverse-noise": False,
        "fix-noise-step": False,
        "classifier-free-guidance": 7.5,
    },
}
